# Scraping Data from a Real Website + Pandas

In [4]:
from bs4 import BeautifulSoup
import requests

In [5]:
url = 'https://companiesmarketcap.com/south-africa/largest-companies-in-south-africa-by-market-cap/'

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

In [6]:
print(soup)

<!DOCTYPE html>
<html lang="en-US">
<head>
<title>Largest South African companies by market capitalization</title>
<meta charset="utf-8"/>
<link href="https://companiesmarketcap.com/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/img/icons/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/img/icons/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/img/icons/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/img/icons/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/img/icons/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/img/icons/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/img/icons/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/img/icons/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/img/icons/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/img/icons/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/img/icons/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/img/icons/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/img/icons/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/img/icons/manifest.json" rel="manifest"/>
<link href="https://companiesmarketcap.com/de/sudafrika/grosste-unternehmen-in-sudafrika-nach-marktkapitalisierung/" hreflang="de" rel="alternate"/>
<link href="https://companiesmarketcap.com/fr/afrique-du-sud/plus-grandes-entreprises-en-afrique-du-sud-par-capitalisation-boursiere/" hreflang="fr" rel="alternate"/>
<link href="https://companiesmarketcap.com/south-africa/largest-companies-in-south-africa-by-market-cap/" hreflang="en-US" rel="alternate"/>
<link href="https://companiesmarketcap.com/eur/south-africa/largest-companies-in-south-africa-by-market-cap/" hreflang="en-IE" rel="alternate"/>
<link href="https://companiesmarketcap.com/inr/south-africa/largest-companies-in-south-africa-by-market-cap/" hreflang="en-IN" rel="alternate"/>
<link href="https://companiesmarketcap.com/gbp/south-africa/largest-companies-in-south-africa-by-market-cap/" hreflang="en-GB" rel="alternate"/>
<link href="https://companiesmarketcap.com/cad/south-africa/largest-companies-in-south-africa-by-market-cap/" hreflang="en-CA" rel="alternate"/>
<link href="https://companiesmarketcap.com/aud/south-africa/largest-companies-in-south-africa-by-market-cap/" hreflang="en-AU" rel="alternate"/>
<link href="https://companiesmarketcap.com/nzd/south-africa/largest-companies-in-south-africa-by-market-cap/" hreflang="en-NZ" rel="alternate"/>
<link href="https://companiesmarketcap.com/hkd/south-africa/largest-companies-in-south-africa-by-market-cap/" hreflang="en-HK" rel="alternate"/>
<link href="https://companiesmarketcap.com/sgd/south-africa/largest-companies-in-south-africa-by-market-cap/" hreflang="en-SG" rel="alternate"/>
<link href="https://companiesmarketcap.com/south-africa/largest-companies-in-south-africa-by-market-cap/" rel="canonical"/>
<meta content="https://companiesmarketcap.com/south-africa/largest-companies-in-south-africa-by-market-cap/" property="og:url"/>
<meta content="INDEX,FOLLOW" name="robots"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="/img/icons/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="en-US" http-equiv="content-language"/>
<meta content="Largest South African companies by market capitalization" property="og:title"/><meta content="website" property="og:type"/>
<meta content="List of the largest companies in South Africa by market capitalization, all rankings are updated daily." property="og:description"/>
<meta content="https://companiesmarketcap.com/logo.png" property="og:image"/>
<meta content="List of the largest companies in South Africa by market capitalization, all rankings are updated daily." name="description"/>
<link href="/bt-replacement.css?v=9" rel="stylesheet" type="text/css"/>
<link href="/css/style.css?v=348" rel="stylesheet" type="text/css"/>
<script>
current_locale = "usd";
current_locale_path = "";

current_marketcap_path = "marketcap";
</script>
<script async="" src="https://cdn.fuseplatform.net/publift/tags/2/3432/fuse.js"></script></head>
<body class="cmkt" id="cmkt">
<div class="row site-header-row">
<div class="site-header">
<span style="display: inline-flex; margin-top: 2px;">
<span class="max-width-720px-hidden">
                        Companies: <span class="font-weight-bold">10,493</span>
                        total market cap: <span class="font-weight-bold"><a class="total-mcap-link" href="/total-marketcap/">$136.388 T</a></span>
</span>
</span>
<div class="header-actions">
<a class="header-button sign-in-button sign-in" href="#">Sign In</a>
<div class="dropdown currency-dropdown">
<a aria-expanded="false" aria-haspopup="true" class="header-button dropdown-toggle" data-toggle="dropdown" href="#" id="languageDropdown">
                        🇺🇸 <span class="responsive-shown-inline">EN</span><span class="responsive-hidden">English</span> </a>
<div aria-labelledby="languageDropdown" class="dropdown-menu currency-menu">
<a class="dropdown-item" href="/de/sudafrika/grosste-unternehmen-in-sudafrika-nach-marktkapitalisierung/" onclick="document.cookie = 'pref_language=DE;  max-age=91536000000; path=/;';">🇩🇪 Deutsch</a><a class="dropdown-item" href="/fr/afrique-du-sud/plus-grandes-entreprises-en-afrique-du-sud-par-capitalisation-boursiere/" onclick="document.cookie = 'pref_language=FR;  max-age=91536000000; path=/;';">🇫🇷 Français</a> </div>
</div>
<div class="dropdown currency-dropdown">
<a aria-expanded="false" aria-haspopup="true" class="header-button dropdown-toggle" data-toggle="dropdown" href="#" id="currencyDropdown">
                        $ USD                        </a>
<div aria-labelledby="currencyDropdown" class="dropdown-menu currency-menu">
<a class="dropdown-item" href="/eur/south-africa/largest-companies-in-south-africa-by-market-cap/" onclick="document.cookie = 'pref_currency=EUR;  max-age=91536000000; path=/;';"><span class="symbol">€</span><span class="currency-code">EUR</span><span class="currency-flag">🇪🇺</span></a><a class="dropdown-item" href="/inr/south-africa/largest-companies-in-south-africa-by-market-cap/" onclick="document.cookie = 'pref_currency=INR;  max-age=91536000000; path=/;';"><span class="symbol">₹</span><span class="currency-code">INR</span><span class="currency-flag">🇮🇳</span></a><a class="dropdown-item" href="/gbp/south-africa/largest-companies-in-south-africa-by-market-cap/" onclick="document.cookie = 'pref_currency=GBP;  max-age=91536000000; path=/;';"><span class="symbol">£</span><span class="currency-code">GBP</span><span class="currency-flag">🇬🇧</span></a><a class="dropdown-item" href="/cad/south-africa/largest-companies-in-south-africa-by-market-cap/" onclick="document.cookie = 'pref_currency=CAD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">CAD</span><span class="currency-flag">🇨🇦</span></a><a class="dropdown-item" href="/aud/south-africa/largest-companies-in-south-africa-by-market-cap/" onclick="document.cookie = 'pref_currency=AUD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">AUD</span><span class="currency-flag">🇦🇺</span></a><a class="dropdown-item" href="/nzd/south-africa/largest-companies-in-south-africa-by-market-cap/" onclick="document.cookie = 'pref_currency=NZD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">NZD</span><span class="currency-flag">🇳🇿</span></a><a class="dropdown-item" href="/hkd/south-africa/largest-companies-in-south-africa-by-market-cap/" onclick="document.cookie = 'pref_currency=HKD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">HKD</span><span class="currency-flag">🇭🇰</span></a><a class="dropdown-item" href="/sgd/south-africa/largest-companies-in-south-africa-by-market-cap/" onclick="document.cookie = 'pref_currency=SGD;  max-age=91536000000; path=/;';"><span class="symbol">$</span><span class="currency-code">SGD</span><span class="currency-flag">🇸🇬</span></a> </div>
</div>
<a class="dark-hidden" href="#" id="light-off-btn" title="change to dark mode">
<svg height="16" viewbox="0 70 1000 1000" width="16" xmlns="http://www.w3.org/2000/svg">
<path d="M525.3,989.5C241.2,989.5,10,758.3,10,474.1c0-196.8,109.6-373.6,285.9-461.4c7.9-3.9,17.5-2.4,23.7,3.8c6.2,6.2,7.9,15.8,4,23.7c-32.2,65.4-48.5,135.7-48.5,208.9c0,261.4,212.7,474.1,474.1,474.1c74,0,145-16.7,211-49.5c7.9-3.9,17.5-2.4,23.7,3.8c6.3,6.3,7.9,15.8,3.9,23.7C900.5,879,723.3,989.5,525.3,989.5z"></path>
</svg>
</a>
<a class="dark-shown" href="#" id="light-on-btn" title="change to light mode">
<svg height="16" viewbox="10 10 220 220" width="16" xmlns="http://www.w3.org/2000/svg">
<path d="M120,189.697c-38.492,0-69.696-31.205-69.696-69.697S81.508,50.303,120,50.303c38.494,0,69.699,31.205,69.699,69.697 S158.494,189.697,120,189.697z M203.975,140L240,120l-36.025-20V140z M36.025,100L0,120l36.025,20V100z M120,240l20-36.025h-40 L120,240z M120,0l-20,36.025h40L120,0z M46.481,165.238l-11.333,39.615l39.616-11.33L46.481,165.238z M165.238,46.477l28.283,28.285 l11.332-39.613L165.238,46.477z M35.148,35.148L46.48,74.762l28.283-28.285L35.148,35.148z M165.238,193.523l39.615,11.33 l-11.332-39.615L165.238,193.523z"></path>
</svg>
</a>
</div>
</div>
</div>
<nav class="navbar nav-bar-companiesmarketcap navbar-expand-lg navbar-light">
<div class="navbar-collapse-container">
<button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
<span class="navbar-toggler-icon"></span>
</button>
<form class="search-form form-inline">
<input aria-label="Company name, ticker..." autocomplete="off" class="form-control search-input" id="search-input" placeholder="Company name, ticker..." type="search"/>
<button class="btn-search" disabled="" onclick="return false;" type="submit"><svg height="18" viewbox="0 0 14 14" width="18" xmlns="http://www.w3.org/2000/svg"><g fill="none" stroke="#6c6c6c" stroke-width="2"><path d="M11.29 11.71l-4-4"></path><circle cx="5" cy="5" r="4"></circle></g></svg></button>
<div class="typeahead-search-results" id="typeahead-search-results"></div>
</form>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
<a class="responsive-hidden" href="/" title="CompaniesMarketCap.com - companies ranked by market capitalization">
<div class="companiesmarketcap-logo"></div>
</a>
<ul class="navbar-nav">
<li class="nav-item">
<a class="nav-link nav-link-companiesmarketcap" href="/">Global ranking</a>
</li>
<li class="nav-item dropdown megamenu-li">
<a aria-expanded="false" aria-haspopup="true" class="nav-link nav-link-companiesmarketcap dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-countries">Ranking by countries</a>
<div aria-labelledby="dropdown-countries" class="dropdown-menu megamenu">
<div class="row">
<div class="col-sm-6 col-lg-3">
<h5>America</h5>
<a class="dropdown-item" href="/usa/largest-companies-in-the-usa-by-market-cap/">🇺🇸 United States</a>
<a class="dropdown-item" href="/canada/largest-companies-in-canada-by-market-cap/">🇨🇦 Canada</a>
<a class="dropdown-item" href="/mexico/largest-companies-in-mexico-by-market-cap/">🇲🇽 Mexico</a>
<a class="dropdown-item" href="/brazil/largest-companies-in-brazil-by-market-cap/">🇧🇷 Brazil</a>
<a class="dropdown-item" href="/chile/largest-companies-in-chile-by-market-cap/">🇨🇱 Chile</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<h5>Europe</h5>
<a class="dropdown-item" href="/european-union/largest-companies-in-the-eu-by-market-cap/">🇪🇺 European Union</a>
<a class="dropdown-item" href="/germany/largest-companies-in-germany-by-market-cap/">🇩🇪 Germany</a>
<a class="dropdown-item" href="/united-kingdom/largest-companies-in-the-uk-by-market-cap/">🇬🇧 United Kingdom</a>
<a class="dropdown-item" href="/france/largest-companies-in-france-by-market-cap/">🇫🇷 France</a>
<a class="dropdown-item" href="/spain/largest-companies-in-spain-by-market-cap/">🇪🇸 Spain</a>
<a class="dropdown-item" href="/netherlands/largest-companies-in-the-netherlands-by-market-cap/">🇳🇱 Netherlands</a>
<a class="dropdown-item" href="/sweden/largest-companies-in-sweden-by-market-cap/">🇸🇪 Sweden</a>
<a class="dropdown-item" href="/italy/largest-companies-in-italy-by-market-cap/">🇮🇹 Italy</a>
<a class="dropdown-item" href="/switzerland/largest-companies-in-switzerland-by-market-cap/">🇨🇭 Switzerland</a>
<a class="dropdown-item" href="/poland/largest-companies-in-poland-by-market-cap/">🇵🇱 Poland</a>
<a class="dropdown-item" href="/finland/largest-companies-in-finland-by-market-cap/">🇫🇮 Finland</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<h5>Asia</h5>
<a class="dropdown-item" href="/china/largest-companies-in-china-by-market-cap/">🇨🇳 China</a>
<a class="dropdown-item" href="/japan/largest-companies-in-japan-by-market-cap/">🇯🇵 Japan</a>
<a class="dropdown-item" href="/south-korea/largest-companies-in-south-korea-by-market-cap/">🇰🇷 South Korea</a>
<a class="dropdown-item" href="/hong-kong/largest-companies-in-hong-kong-by-market-cap/">🇭🇰 Hong Kong</a>
<a class="dropdown-item" href="/singapore/largest-companies-in-singapore-by-market-cap/">🇸🇬 Singapore</a>
<a class="dropdown-item" href="/indonesia/largest-companies-in-indonesia-by-market-cap/">🇮🇩 Indonesia</a>
<a class="dropdown-item" href="/india/largest-companies-in-india-by-market-cap/">🇮🇳 India</a>
<a class="dropdown-item" href="/malaysia/largest-companies-in-malaysia-by-market-cap/">🇲🇾 Malaysia</a>
<a class="dropdown-item" href="/taiwan/largest-companies-in-taiwan-by-market-cap/">🇹🇼 Taiwan</a>
<a class="dropdown-item" href="/thailand/largest-companies-in-thailand-by-market-cap/">🇹🇭 Thailand</a>
<a class="dropdown-item" href="/vietnam/largest-companies-in-vietnam-by-market-cap/">🇻🇳 Vietnam</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<h5>Others</h5>
<a class="dropdown-item" href="/australia/largest-companies-in-australia-by-market-cap/">🇦🇺 Australia</a>
<a class="dropdown-item" href="/new-zealand/largest-companies-in-new-zealand-by-market-cap/">🇳🇿 New Zealand</a>
<a class="dropdown-item" href="/israel/largest-companies-in-israel-by-market-cap/">🇮🇱 Israel</a>
<a class="dropdown-item" href="/saudi-arabia/largest-companies-in-saudi-arabia-by-market-cap/">🇸🇦 Saudi Arabia</a>
<a class="dropdown-item" href="/turkey/largest-companies-in-turkey-by-market-cap/">🇹🇷 Turkey</a>
<a class="dropdown-item" href="/russia/largest-companies-in-russia-by-market-cap/">🇷🇺 Russia</a>
<a class="dropdown-item" href="/south-africa/largest-companies-in-south-africa-by-market-cap/">🇿🇦 South Africa</a>
<a class="dropdown-item" href="/all-countries/"><strong>&gt;&gt; All Countries</strong></a>
</div>
</div>
</div>
</li>
<li class="nav-item dropdown megamenu-li">
<a aria-expanded="false" aria-haspopup="true" class="nav-link nav-link-companiesmarketcap dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-categories">Ranking by categories</a>
<div aria-labelledby="dropdown-categories" class="dropdown-menu megamenu">
<div class="row">
<div class="col-sm-6 col-lg-3">
<a class="dropdown-item" href="/assets-by-market-cap/">🏆 All assets by Market Cap</a>
<a class="dropdown-item" href="/automakers/largest-automakers-by-market-cap/">🚗 Automakers</a>
<a class="dropdown-item" href="/airlines/largest-airlines-by-market-cap/">✈️  Airlines</a>
<a class="dropdown-item" href="/airports/largest-airport-operating-companies-by-market-cap/">🛫 Airports</a>
<a class="dropdown-item" href="/aircraft-manufacturers/largest-aircraft-manufacturers-by-market-cap/">✈️  Aircraft manufacturers</a>
<a class="dropdown-item" href="/banks/largest-banks-by-market-cap/">🏦 Banks</a>
<a class="dropdown-item" href="/hotels/largest-hotel-companies-by-market-cap/">🏨 Hotels</a>
<a class="dropdown-item" href="/pharmaceuticals/largest-pharmaceutical-companies-by-market-cap/">💊 Pharmaceuticals</a>
<a class="dropdown-item" href="/e-commerce/largest-e-commerce-companies-by-market-cap/">🛒 E-Commerce</a>
<a class="dropdown-item" href="/healthcare/largest-healthcare-companies-by-market-cap/">⚕️ Healthcare</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<a class="dropdown-item" href="/delivery-services/largest-delivery-companies-by-market-cap/">📦 Courier services</a>
<a class="dropdown-item" href="/media-press/largest-media-and-press-companies-by-market-cap/">📰 Media/Press</a>
<a class="dropdown-item" href="/alcoholic-beverages/largest-alcoholic-beverage-companies-by-market-cap/">🍷 Alcoholic beverages</a>
<a class="dropdown-item" href="/beverages/largest-beverage-companies-by-market-cap/">🥤 Beverages</a>
<a class="dropdown-item" href="/clothing/largest-clothing-companies-by-market-cap/">👚 Clothing</a>
<a class="dropdown-item" href="/mining/largest-mining-companies-by-market-cap/">⛏️ Mining</a>
<a class="dropdown-item" href="/railways/largest-railways-companies-by-market-cap/">🚂 Railways</a>
<a class="dropdown-item" href="/insurance/largest-insurance-companies-by-market-cap/">🏦 Insurance</a>
<a class="dropdown-item" href="/real-estate/largest-real-estate-companies-by-market-cap/">🏠 Real estate</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<a class="dropdown-item" href="/ports/largest-port-operating-companies-by-market-cap/">⚓ Ports</a>
<a class="dropdown-item" href="/professional-services/largest-professional-service-companies-by-market-cap/">💼 Professional services</a>
<a class="dropdown-item" href="/food/largest-food-companies-by-market-cap/">🍴 Food</a>
<a class="dropdown-item" href="/restaurant-chains/largest-restaurant-chain-companies-by-market-cap/">🍔 Restaurant chains</a>
<a class="dropdown-item" href="/software/largest-software-companies-by-market-cap/">‍💻 Software</a>
<a class="dropdown-item" href="/semiconductors/largest-semiconductor-companies-by-market-cap/">📟 Semiconductors</a>
<a class="dropdown-item" href="/tobacco/largest-tobacco-companies-by-market-cap/"> 🚬 Tobacco</a>
<a class="dropdown-item" href="/financial-services/largest-financial-service-companies-by-market-cap/">💳 Financial services</a>
<a class="dropdown-item" href="/oil-gas/largest-oil-and-gas-companies-by-market-cap/">🛢 Oil&amp;Gas</a>
<a class="dropdown-item" href="/electricity/largest-electricity-companies-by-market-cap/">🔋 Electricity</a>
</div>
<div class="col-sm-6 col-lg-3 border-left">
<a class="dropdown-item" href="/chemicals/largest-chemical-companies-by-market-cap/">🧪 Chemicals</a>
<a class="dropdown-item" href="/investment/largest-investment-companies-by-market-cap/">💰 Investment</a>
<a class="dropdown-item" href="/telecommunication/largest-telecommunication-companies-by-market-cap/">📡 Telecommunication</a>
<a class="dropdown-item" href="/retail/largest-retail-companies-by-market-cap/">🛍️ Retail</a>
<a class="dropdown-item" href="/internet/largest-internet-companies-by-market-cap/">🖥️ Internet</a>
<a class="dropdown-item" href="/construction/largest-construction-companies-by-market-cap/">🏗 Construction</a>
<a class="dropdown-item" href="/video-games/largest-video-game-companies-by-market-cap/">🎮 Video Game</a>
<a class="dropdown-item" href="/tech/largest-tech-companies-by-market-cap/">💻 Tech</a>
<a class="dropdown-item" href="/artificial-intelligence/largest-ai-companies-by-marketcap/">🦾 AI</a>
<a class="dropdown-item" href="/all-categories/"><strong>&gt;&gt; All Categories</strong></a>
</div>
</div>
</div>
</li>
<li class="nav-item dropdown megamenu-li">

In [7]:
table = soup.find_all('table', class_ = 'default-table table marketcap-table dataTable')

In [8]:
print(table)

[<table class="default-table table marketcap-table dataTable" style="width:100%">
<thead><tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr></thead> <tbody>
<tr><td class="fav"><img alt="favorite icon" data-id="7980" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="1">1</td><td class="name-td"><div class="logo-container"><img alt="AngloGold Ashanti
 logo" class="company-logo" data-img-dark-path="/img/company-logos/64/AU.D.png" data-img-path="/img/company-logos/64/AU.png" loading="lazy" src="/img/company-logos/64/AU.png"/></div><div class="name-div"><a href="/anglogold-ashanti/marketcap/"><div class="company-name">AngloGold Ashanti
</div><div class="company-code"><span class="rank d-none"></span>AU</div></a></div></td><td class="td-right" data-sort="53804273664"><span class="currency-symbol-left">$</span>53.80 B</td><td class="td-right" data-sort="10654">$106.54</td><td class="rh-sm" data-sort="-125"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>1.25%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,30 L5,27 L10,25 L15,23 L20,16 L25,26 L30,41 L35,39 L40,33 L45,32 L50,35 L55,29 L60,26 L65,24 L70,20 L75,28 L80,23 L85,23 L90,27 L95,24 L100,25 L105,18 L110,11 L115,7 L120,7 L125,5 L130,4 L135,3 L140,17 L145,19 L150,25 L155,26"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="7499" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="2">2</td><td class="name-td"><div class="logo-container"><img alt="Gold Fields
 logo" class="company-logo" data-img-dark-path="/img/company-logos/64/GFI.D.png" data-img-path="/img/company-logos/64/GFI.png" loading="lazy" src="/img/company-logos/64/GFI.png"/></div><div class="name-div"><a href="/gold-fields/marketcap/"><div class="company-name">Gold Fields
</div><div class="company-code"><span class="rank d-none"></span>GFI</div></a></div></td><td class="td-right" data-sort="45145022464"><span class="currency-symbol-left">$</span>45.14 B</td><td class="td-right" data-sort="5044">$50.44</td><td class="rh-sm" data-sort="68"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.68%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,34 L5,30 L10,25 L15,20 L20,3 L25,13 L30,40 L35,41 L40,33 L45,32 L50,41 L55,29 L60,21 L65,22 L70,17 L75,34 L80,26 L85,26 L90,36 L95,33 L100,31 L105,27 L110,18 L115,18 L120,14 L125,13 L130,12 L135,15 L140,37 L145,37 L150,41 L155,39"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="555" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="3">3</td><td class="name-td"><div class="logo-container"><img alt="Naspers logo" class="company-logo" data-img-dark-path="/img/company-logos/64/NPSNY.D.png" data-img-path="/img/company-logos/64/NPSNY.png" loading="lazy" src="/img/company-logos/64/NPSNY.png"/></div><div class="name-div"><a href="/naspers/marketcap/"><div class="company-name">Naspers</div><div class="company-code"><span class="rank d-none"></span>NPSNY</div></a></div></td><td class="td-right" data-sort="40615297024"><span class="currency-symbol-left">$</span>40.61 B</td><td class="td-right" data-sort="1058">$10.58</td><td class="rh-sm" data-sort="-47"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.47%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,7 L5,8 L10,9 L15,3 L20,4 L25,4 L30,13 L35,12 L40,16 L45,22 L50,24 L55,17 L60,17 L65,22 L70,26 L75,28 L80,29 L85,29 L90,30 L95,28 L100,29 L105,27 L110,25 L115,28 L120,27 L125,30 L130,30 L135,34 L140,41 L145,35 L150,38 L155,39"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56546" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="4">4</td><td class="name-td"><div class="logo-container"><img alt="Capitec Bank logo" class="company-logo" data-img-dark-path="/img/company-logos/64/CPI.JO.D.png" data-img-path="/img/company-logos/64/CPI.JO.png" loading="lazy" src="/img/company-logos/64/CPI.JO.png"/></div><div class="name-div"><a href="/capitec-bank/marketcap/"><div class="company-name">Capitec Bank</div><div class="company-code"><span class="rank d-none"></span>CPI.JO</div></a></div></td><td class="td-right" data-sort="29375339100"><span class="currency-symbol-left">$</span>29.37 B</td><td class="td-right" data-sort="25366">$253.66</td><td class="rh-sm" data-sort="-589"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>5.89%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,32 L5,31 L10,33 L15,29 L20,29 L25,26 L30,32 L35,25 L40,25 L45,27 L50,27 L55,25 L60,20 L65,17 L70,15 L75,11 L80,12 L85,10 L90,11 L95,3 L100,6 L105,7 L110,7 L115,6 L120,10 L125,6 L130,6 L135,12 L140,24 L145,22 L150,24 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="11487" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="5">5</td><td class="name-td"><div class="logo-container"><img alt="FirstRand logo" class="company-logo" loading="lazy" src="/img/company-logos/64/FSR.JO.png"/></div><div class="name-div"><a href="/firstrand/marketcap/"><div class="company-name">FirstRand</div><div class="company-code"><span class="rank d-none"></span>FSR.JO</div></a></div></td><td class="td-right" data-sort="29298359900"><span class="currency-symbol-left">$</span>29.29 B</td><td class="td-right" data-sort="523.95">$5.24</td><td class="rh-sm" data-sort="-623"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>6.23%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,23 L5,27 L10,28 L15,23 L20,26 L25,23 L30,24 L35,20 L40,19 L45,21 L50,21 L55,19 L60,21 L65,18 L70,16 L75,15 L80,17 L85,14 L90,16 L95,7 L100,8 L105,7 L110,9 L115,5 L120,10 L125,3 L130,4 L135,14 L140,27 L145,24 L150,24 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56337" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="6">6</td><td class="name-td"><div class="logo-container"><img alt="Standard Bank Group logo" class="company-logo" loading="lazy" src="/img/company-logos/64/SBK.JO.png"/></div><div class="name-div"><a href="/standard-bank-group/marketcap/"><div class="company-name">Standard Bank Group</div><div class="company-code"><span class="rank d-none"></span>SBK.JO</div></a></div></td><td class="td-right" data-sort="28469708700"><span class="currency-symbol-left">$</span>28.46 B</td><td class="td-right" data-sort="1758.33">$17.58</td><td class="rh-sm" data-sort="-499"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>4.99%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,36 L5,36 L10,34 L15,32 L20,35 L25,33 L30,33 L35,24 L40,21 L45,22 L50,20 L55,21 L60,22 L65,18 L70,18 L75,16 L80,16 L85,14 L90,12 L95,4 L100,4 L105,9 L110,7 L115,5 L120,7 L125,3 L130,7 L135,8 L140,26 L145,21 L150,24 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56554" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="7">7</td><td class="name-td"><div class="logo-container"><img alt="MTN Group logo" class="company-logo" data-img-dark-path="/img/company-logos/64/MTN.JO.D.png" data-img-path="/img/company-logos/64/MTN.JO.png" loading="lazy" src="/img/company-logos/64/MTN.JO.png"/></div><div class="name-div"><a href="/mtn-group/marketcap/"><div class="company-name">MTN Group</div><div class="company-code"><span class="rank d-none"></span>MTN.JO</div></a></div></td><td class="td-right" data-sort="20899611500"><span class="currency-symbol-left">$</span>20.89 B</td><td class="td-right" data-sort="1156.84">$11.57</td><td class="rh-sm" data-sort="-479"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>4.79%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,32 L5,41 L10,34 L15,33 L20,37 L25,36 L30,35 L35,31 L40,28 L45,29 L50,41 L55,32 L60,27 L65,23 L70,22 L75,19 L80,22 L85,19 L90,19 L95,14 L100,20 L105,16 L110,19 L115,16 L120,7 L125,9 L130,5 L135,3 L140,13 L145,14 L150,11 L155,23"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="34668" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="8">8</td><td class="name-td"><div class="logo-container"><img alt="Vodacom
 logo" class="company-logo" loading="lazy" src="/img/company-logos/64/VOD.JO.png"/></div><div class="name-div"><a href="/vodacom/marketcap/"><div class="company-name">Vodacom
</div><div class="company-code"><span class="rank d-none"></span>VOD.JO</div></a></div></td><td class="td-right" data-sort="18083435100"><span class="currency-symbol-left">$</span>18.08 B</td><td class="td-right" data-sort="935.952">$9.36</td><td class="rh-sm" data-sort="-241"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>2.41%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,38 L5,41 L10,31 L15,31 L20,37 L25,35 L30,33 L35,27 L40,22 L45,24 L50,29 L55,25 L60,22 L65,21 L70,23 L75,20 L80,22 L85,17 L90,17 L95,12 L100,17 L105,14 L110,13 L115,7 L120,5 L125,11 L130,6 L135,3 L140,15 L145,12 L150,14 L155,22"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56600" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="9">9</td><td class="name-td"><div class="logo-container"><img alt="Impala Platinum logo" class="company-logo" data-img-dark-path="/img/company-logos/64/IMP.JO.D.png" data-img-path="/img/company-logos/64/IMP.JO.png" loading="lazy" src="/img/company-logos/64/IMP.JO.png"/></div><div class="name-div"><a href="/impala-platinum/marketcap/"><div class="company-name">Impala Platinum</div><div class="company-code"><span class="rank d-none"></span>IMP.JO</div></a></div></td><td class="td-right" data-sort="14430171200"><span class="currency-symbol-left">$</span>14.43 B</td><td class="td-right" data-sort="1608.72">$16.09</td><td class="rh-sm" data-sort="-195"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>1.95%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,16 L5,10 L10,3 L15,6 L20,3 L25,4 L30,22 L35,33 L40,27 L45,25 L50,35 L55,38 L60,36 L65,35 L70,31 L75,32 L80,38 L85,39 L90,40 L95,34 L100,37 L105,32 L110,27 L115,25 L120,20 L125,15 L130,8 L135,12 L140,34 L145,31 L150,39 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="3197" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="10">10</td><td class="name-td"><div class="logo-container"><img alt="Harmony Gold logo" class="company-logo" loading="lazy" src="/img/company-logos/64/HMY.png"/></div><div class="name-div"><a href="/harmony-gold/marketcap/"><div class="company-name">Harmony Gold</div><div class="company-code"><span class="rank d-none"></span>HMY</div></a></div></td><td class="td-right" data-sort="12235589632"><span class="currency-symbol-left">$</span>12.23 B</td><td class="td-right" data-sort="1959">$19.59</td><td class="rh-sm" data-sort="20"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.20%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,20 L5,18 L10,17 L15,14 L20,3 L25,12 L30,30 L35,32 L40,30 L45,31 L50,41 L55,35 L60,29 L65,30 L70,28 L75,39 L80,32 L85,32 L90,39 L95,37 L100,36 L105,32 L110,27 L115,29 L120,29 L125,23 L130,22 L135,23 L140,34 L145,36 L150,40 L155,40"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56504" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="11">11</td><td class="name-td"><div class="logo-container"><img alt="Sanlam logo" class="company-logo" data-img-dark-path="/img/company-logos/64/SLM.JO.D.png" data-img-path="/img/company-logos/64/SLM.JO.png" loading="lazy" src="/img/company-logos/64/SLM.JO.png"/></div><div class="name-div"><a href="/sanlam/marketcap/"><div class="company-name">Sanlam</div><div class="company-code"><span class="rank d-none"></span>SLM.JO</div></a></div></td><td class="td-right" data-sort="11583542600"><span class="currency-symbol-left">$</span>11.58 B</td><td class="td-right" data-sort="554.859">$5.55</td><td class="rh-sm" data-sort="-355"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>3.55%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,13 L5,14 L10,11 L15,11 L20,15 L25,9 L30,18 L35,9 L40,8 L45,17 L50,19 L55,19 L60,19 L65,14 L70,17 L75,15 L80,17 L85,12 L90,11 L95,5 L100,6 L105,5 L110,5 L115,4 L120,7 L125,3 L130,5 L135,11 L140,21 L145,19 L150,32 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56775" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="12">12</td><td class="name-td"><div class="logo-container"><img alt="Discovery Limited logo" class="company-logo" data-img-dark-path="/img/company-logos/64/DSY.JO.D.png" data-img-path="/img/company-logos/64/DSY.JO.png" loading="lazy" src="/img/company-logos/64/DSY.JO.png"/></div><div class="name-div"><a href="/discovery-limited/marketcap/"><div class="company-name">Discovery Limited</div><div class="company-code"><span class="rank d-none"></span>DSY.JO</div></a></div></td><td class="td-right" data-sort="10274029900"><span class="currency-symbol-left">$</span>10.27 B</td><td class="td-right" data-sort="1527.51">$15.28</td><td class="rh-sm" data-sort="-235"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>2.35%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,38 L5,39 L10,41 L15,39 L20,40 L25,35 L30,33 L35,30 L40,29 L45,31 L50,32 L55,30 L60,32 L65,25 L70,28 L75,29 L80,35 L85,31 L90,31 L95,26 L100,28 L105,27 L110,27 L115,23 L120,24 L125,3 L130,4 L135,8 L140,6 L145,8 L150,6 L155,13"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="6973" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="13">13</td><td class="name-td"><div class="logo-container"><img alt="Sibanye-Stillwater
 logo" class="company-logo" data-img-dark-path="/img/company-logos/64/SBSW.D.png" data-img-path="/img/company-logos/64/SBSW.png" loading="lazy" src="/img/company-logos/64/SBSW.png"/></div><div class="name-div"><a href="/sibanye-stillwater/marketcap/"><div class="company-name">Sibanye-Stillwater

In [9]:
soup.find('table')

<table class="default-table table marketcap-table dataTable" style="width:100%">
<thead><tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr></thead> <tbody>
<tr><td class="fav"><img alt="favorite icon" data-id="7980" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="1">1</td><td class="name-td"><div class="logo-container"><img alt="AngloGold Ashanti
 logo" class="company-logo" data-img-dark-path="/img/company-logos/64/AU.D.png" data-img-path="/img/company-logos/64/AU.png" loading="lazy" src="/img/company-logos/64/AU.png"/></div><div class="name-div"><a href="/anglogold-ashanti/marketcap/"><div class="company-name">AngloGold Ashanti
</div><div class="company-code"><span class="rank d-none"></span>AU</div></a></div></td><td class="td-right" data-sort="53804273664"><span class="currency-symbol-left">$</span>53.80 B</td><td class="td-right" data-sort="10654">$106.54</td><td class="rh-sm" data-sort="-125"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>1.25%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,30 L5,27 L10,25 L15,23 L20,16 L25,26 L30,41 L35,39 L40,33 L45,32 L50,35 L55,29 L60,26 L65,24 L70,20 L75,28 L80,23 L85,23 L90,27 L95,24 L100,25 L105,18 L110,11 L115,7 L120,7 L125,5 L130,4 L135,3 L140,17 L145,19 L150,25 L155,26"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="7499" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="2">2</td><td class="name-td"><div class="logo-container"><img alt="Gold Fields
 logo" class="company-logo" data-img-dark-path="/img/company-logos/64/GFI.D.png" data-img-path="/img/company-logos/64/GFI.png" loading="lazy" src="/img/company-logos/64/GFI.png"/></div><div class="name-div"><a href="/gold-fields/marketcap/"><div class="company-name">Gold Fields
</div><div class="company-code"><span class="rank d-none"></span>GFI</div></a></div></td><td class="td-right" data-sort="45145022464"><span class="currency-symbol-left">$</span>45.14 B</td><td class="td-right" data-sort="5044">$50.44</td><td class="rh-sm" data-sort="68"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.68%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,34 L5,30 L10,25 L15,20 L20,3 L25,13 L30,40 L35,41 L40,33 L45,32 L50,41 L55,29 L60,21 L65,22 L70,17 L75,34 L80,26 L85,26 L90,36 L95,33 L100,31 L105,27 L110,18 L115,18 L120,14 L125,13 L130,12 L135,15 L140,37 L145,37 L150,41 L155,39"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="555" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="3">3</td><td class="name-td"><div class="logo-container"><img alt="Naspers logo" class="company-logo" data-img-dark-path="/img/company-logos/64/NPSNY.D.png" data-img-path="/img/company-logos/64/NPSNY.png" loading="lazy" src="/img/company-logos/64/NPSNY.png"/></div><div class="name-div"><a href="/naspers/marketcap/"><div class="company-name">Naspers</div><div class="company-code"><span class="rank d-none"></span>NPSNY</div></a></div></td><td class="td-right" data-sort="40615297024"><span class="currency-symbol-left">$</span>40.61 B</td><td class="td-right" data-sort="1058">$10.58</td><td class="rh-sm" data-sort="-47"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.47%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,7 L5,8 L10,9 L15,3 L20,4 L25,4 L30,13 L35,12 L40,16 L45,22 L50,24 L55,17 L60,17 L65,22 L70,26 L75,28 L80,29 L85,29 L90,30 L95,28 L100,29 L105,27 L110,25 L115,28 L120,27 L125,30 L130,30 L135,34 L140,41 L145,35 L150,38 L155,39"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56546" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="4">4</td><td class="name-td"><div class="logo-container"><img alt="Capitec Bank logo" class="company-logo" data-img-dark-path="/img/company-logos/64/CPI.JO.D.png" data-img-path="/img/company-logos/64/CPI.JO.png" loading="lazy" src="/img/company-logos/64/CPI.JO.png"/></div><div class="name-div"><a href="/capitec-bank/marketcap/"><div class="company-name">Capitec Bank</div><div class="company-code"><span class="rank d-none"></span>CPI.JO</div></a></div></td><td class="td-right" data-sort="29375339100"><span class="currency-symbol-left">$</span>29.37 B</td><td class="td-right" data-sort="25366">$253.66</td><td class="rh-sm" data-sort="-589"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>5.89%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,32 L5,31 L10,33 L15,29 L20,29 L25,26 L30,32 L35,25 L40,25 L45,27 L50,27 L55,25 L60,20 L65,17 L70,15 L75,11 L80,12 L85,10 L90,11 L95,3 L100,6 L105,7 L110,7 L115,6 L120,10 L125,6 L130,6 L135,12 L140,24 L145,22 L150,24 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="11487" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="5">5</td><td class="name-td"><div class="logo-container"><img alt="FirstRand logo" class="company-logo" loading="lazy" src="/img/company-logos/64/FSR.JO.png"/></div><div class="name-div"><a href="/firstrand/marketcap/"><div class="company-name">FirstRand</div><div class="company-code"><span class="rank d-none"></span>FSR.JO</div></a></div></td><td class="td-right" data-sort="29298359900"><span class="currency-symbol-left">$</span>29.29 B</td><td class="td-right" data-sort="523.95">$5.24</td><td class="rh-sm" data-sort="-623"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>6.23%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,23 L5,27 L10,28 L15,23 L20,26 L25,23 L30,24 L35,20 L40,19 L45,21 L50,21 L55,19 L60,21 L65,18 L70,16 L75,15 L80,17 L85,14 L90,16 L95,7 L100,8 L105,7 L110,9 L115,5 L120,10 L125,3 L130,4 L135,14 L140,27 L145,24 L150,24 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56337" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="6">6</td><td class="name-td"><div class="logo-container"><img alt="Standard Bank Group logo" class="company-logo" loading="lazy" src="/img/company-logos/64/SBK.JO.png"/></div><div class="name-div"><a href="/standard-bank-group/marketcap/"><div class="company-name">Standard Bank Group</div><div class="company-code"><span class="rank d-none"></span>SBK.JO</div></a></div></td><td class="td-right" data-sort="28469708700"><span class="currency-symbol-left">$</span>28.46 B</td><td class="td-right" data-sort="1758.33">$17.58</td><td class="rh-sm" data-sort="-499"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>4.99%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,36 L5,36 L10,34 L15,32 L20,35 L25,33 L30,33 L35,24 L40,21 L45,22 L50,20 L55,21 L60,22 L65,18 L70,18 L75,16 L80,16 L85,14 L90,12 L95,4 L100,4 L105,9 L110,7 L115,5 L120,7 L125,3 L130,7 L135,8 L140,26 L145,21 L150,24 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56554" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="7">7</td><td class="name-td"><div class="logo-container"><img alt="MTN Group logo" class="company-logo" data-img-dark-path="/img/company-logos/64/MTN.JO.D.png" data-img-path="/img/company-logos/64/MTN.JO.png" loading="lazy" src="/img/company-logos/64/MTN.JO.png"/></div><div class="name-div"><a href="/mtn-group/marketcap/"><div class="company-name">MTN Group</div><div class="company-code"><span class="rank d-none"></span>MTN.JO</div></a></div></td><td class="td-right" data-sort="20899611500"><span class="currency-symbol-left">$</span>20.89 B</td><td class="td-right" data-sort="1156.84">$11.57</td><td class="rh-sm" data-sort="-479"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>4.79%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,32 L5,41 L10,34 L15,33 L20,37 L25,36 L30,35 L35,31 L40,28 L45,29 L50,41 L55,32 L60,27 L65,23 L70,22 L75,19 L80,22 L85,19 L90,19 L95,14 L100,20 L105,16 L110,19 L115,16 L120,7 L125,9 L130,5 L135,3 L140,13 L145,14 L150,11 L155,23"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="34668" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="8">8</td><td class="name-td"><div class="logo-container"><img alt="Vodacom
 logo" class="company-logo" loading="lazy" src="/img/company-logos/64/VOD.JO.png"/></div><div class="name-div"><a href="/vodacom/marketcap/"><div class="company-name">Vodacom
</div><div class="company-code"><span class="rank d-none"></span>VOD.JO</div></a></div></td><td class="td-right" data-sort="18083435100"><span class="currency-symbol-left">$</span>18.08 B</td><td class="td-right" data-sort="935.952">$9.36</td><td class="rh-sm" data-sort="-241"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>2.41%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,38 L5,41 L10,31 L15,31 L20,37 L25,35 L30,33 L35,27 L40,22 L45,24 L50,29 L55,25 L60,22 L65,21 L70,23 L75,20 L80,22 L85,17 L90,17 L95,12 L100,17 L105,14 L110,13 L115,7 L120,5 L125,11 L130,6 L135,3 L140,15 L145,12 L150,14 L155,22"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56600" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="9">9</td><td class="name-td"><div class="logo-container"><img alt="Impala Platinum logo" class="company-logo" data-img-dark-path="/img/company-logos/64/IMP.JO.D.png" data-img-path="/img/company-logos/64/IMP.JO.png" loading="lazy" src="/img/company-logos/64/IMP.JO.png"/></div><div class="name-div"><a href="/impala-platinum/marketcap/"><div class="company-name">Impala Platinum</div><div class="company-code"><span class="rank d-none"></span>IMP.JO</div></a></div></td><td class="td-right" data-sort="14430171200"><span class="currency-symbol-left">$</span>14.43 B</td><td class="td-right" data-sort="1608.72">$16.09</td><td class="rh-sm" data-sort="-195"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>1.95%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,16 L5,10 L10,3 L15,6 L20,3 L25,4 L30,22 L35,33 L40,27 L45,25 L50,35 L55,38 L60,36 L65,35 L70,31 L75,32 L80,38 L85,39 L90,40 L95,34 L100,37 L105,32 L110,27 L115,25 L120,20 L125,15 L130,8 L135,12 L140,34 L145,31 L150,39 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="3197" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="10">10</td><td class="name-td"><div class="logo-container"><img alt="Harmony Gold logo" class="company-logo" loading="lazy" src="/img/company-logos/64/HMY.png"/></div><div class="name-div"><a href="/harmony-gold/marketcap/"><div class="company-name">Harmony Gold</div><div class="company-code"><span class="rank d-none"></span>HMY</div></a></div></td><td class="td-right" data-sort="12235589632"><span class="currency-symbol-left">$</span>12.23 B</td><td class="td-right" data-sort="1959">$19.59</td><td class="rh-sm" data-sort="20"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.20%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,20 L5,18 L10,17 L15,14 L20,3 L25,12 L30,30 L35,32 L40,30 L45,31 L50,41 L55,35 L60,29 L65,30 L70,28 L75,39 L80,32 L85,32 L90,39 L95,37 L100,36 L105,32 L110,27 L115,29 L120,29 L125,23 L130,22 L135,23 L140,34 L145,36 L150,40 L155,40"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56504" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="11">11</td><td class="name-td"><div class="logo-container"><img alt="Sanlam logo" class="company-logo" data-img-dark-path="/img/company-logos/64/SLM.JO.D.png" data-img-path="/img/company-logos/64/SLM.JO.png" loading="lazy" src="/img/company-logos/64/SLM.JO.png"/></div><div class="name-div"><a href="/sanlam/marketcap/"><div class="company-name">Sanlam</div><div class="company-code"><span class="rank d-none"></span>SLM.JO</div></a></div></td><td class="td-right" data-sort="11583542600"><span class="currency-symbol-left">$</span>11.58 B</td><td class="td-right" data-sort="554.859">$5.55</td><td class="rh-sm" data-sort="-355"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>3.55%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,13 L5,14 L10,11 L15,11 L20,15 L25,9 L30,18 L35,9 L40,8 L45,17 L50,19 L55,19 L60,19 L65,14 L70,17 L75,15 L80,17 L85,12 L90,11 L95,5 L100,6 L105,5 L110,5 L115,4 L120,7 L125,3 L130,5 L135,11 L140,21 L145,19 L150,32 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56775" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="12">12</td><td class="name-td"><div class="logo-container"><img alt="Discovery Limited logo" class="company-logo" data-img-dark-path="/img/company-logos/64/DSY.JO.D.png" data-img-path="/img/company-logos/64/DSY.JO.png" loading="lazy" src="/img/company-logos/64/DSY.JO.png"/></div><div class="name-div"><a href="/discovery-limited/marketcap/"><div class="company-name">Discovery Limited</div><div class="company-code"><span class="rank d-none"></span>DSY.JO</div></a></div></td><td class="td-right" data-sort="10274029900"><span class="currency-symbol-left">$</span>10.27 B</td><td class="td-right" data-sort="1527.51">$15.28</td><td class="rh-sm" data-sort="-235"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>2.35%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,38 L5,39 L10,41 L15,39 L20,40 L25,35 L30,33 L35,30 L40,29 L45,31 L50,32 L55,30 L60,32 L65,25 L70,28 L75,29 L80,35 L85,31 L90,31 L95,26 L100,28 L105,27 L110,27 L115,23 L120,24 L125,3 L130,4 L135,8 L140,6 L145,8 L150,6 L155,13"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="6973" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="13">13</td><td class="name-td"><div class="logo-container"><img alt="Sibanye-Stillwater
 logo" class="company-logo" data-img-dark-path="/img/company-logos/64/SBSW.D.png" data-img-path="/img/company-logos/64/SBSW.png" loading="lazy" src="/img/company-logos/64/SBSW.png"/></div><div class="name-div"><a href="/sibanye-stillwater/marketcap/"><div class="company-name">Sibanye-Stillwater

In [11]:
table = soup.find_all('table')[0]

In [12]:
print(table)

<table class="default-table table marketcap-table dataTable" style="width:100%">
<thead><tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr></thead> <tbody>
<tr><td class="fav"><img alt="favorite icon" data-id="7980" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="1">1</td><td class="name-td"><div class="logo-container"><img alt="AngloGold Ashanti
 logo" class="company-logo" data-img-dark-path="/img/company-logos/64/AU.D.png" data-img-path="/img/company-logos/64/AU.png" loading="lazy" src="/img/company-logos/64/AU.png"/></div><div class="name-div"><a href="/anglogold-ashanti/marketcap/"><div class="company-name">AngloGold Ashanti
</div><div class="company-code"><span class="rank d-none"></span>AU</div></a></div></td><td class="td-right" data-sort="53804273664"><span class="currency-symbol-left">$</span>53.80 B</td><td class="td-right" data-sort="10654">$106.54</td><td class="rh-sm" data-sort="-125"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>1.25%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,30 L5,27 L10,25 L15,23 L20,16 L25,26 L30,41 L35,39 L40,33 L45,32 L50,35 L55,29 L60,26 L65,24 L70,20 L75,28 L80,23 L85,23 L90,27 L95,24 L100,25 L105,18 L110,11 L115,7 L120,7 L125,5 L130,4 L135,3 L140,17 L145,19 L150,25 L155,26"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="7499" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="2">2</td><td class="name-td"><div class="logo-container"><img alt="Gold Fields
 logo" class="company-logo" data-img-dark-path="/img/company-logos/64/GFI.D.png" data-img-path="/img/company-logos/64/GFI.png" loading="lazy" src="/img/company-logos/64/GFI.png"/></div><div class="name-div"><a href="/gold-fields/marketcap/"><div class="company-name">Gold Fields
</div><div class="company-code"><span class="rank d-none"></span>GFI</div></a></div></td><td class="td-right" data-sort="45145022464"><span class="currency-symbol-left">$</span>45.14 B</td><td class="td-right" data-sort="5044">$50.44</td><td class="rh-sm" data-sort="68"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.68%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,34 L5,30 L10,25 L15,20 L20,3 L25,13 L30,40 L35,41 L40,33 L45,32 L50,41 L55,29 L60,21 L65,22 L70,17 L75,34 L80,26 L85,26 L90,36 L95,33 L100,31 L105,27 L110,18 L115,18 L120,14 L125,13 L130,12 L135,15 L140,37 L145,37 L150,41 L155,39"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="555" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="3">3</td><td class="name-td"><div class="logo-container"><img alt="Naspers logo" class="company-logo" data-img-dark-path="/img/company-logos/64/NPSNY.D.png" data-img-path="/img/company-logos/64/NPSNY.png" loading="lazy" src="/img/company-logos/64/NPSNY.png"/></div><div class="name-div"><a href="/naspers/marketcap/"><div class="company-name">Naspers</div><div class="company-code"><span class="rank d-none"></span>NPSNY</div></a></div></td><td class="td-right" data-sort="40615297024"><span class="currency-symbol-left">$</span>40.61 B</td><td class="td-right" data-sort="1058">$10.58</td><td class="rh-sm" data-sort="-47"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.47%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,7 L5,8 L10,9 L15,3 L20,4 L25,4 L30,13 L35,12 L40,16 L45,22 L50,24 L55,17 L60,17 L65,22 L70,26 L75,28 L80,29 L85,29 L90,30 L95,28 L100,29 L105,27 L110,25 L115,28 L120,27 L125,30 L130,30 L135,34 L140,41 L145,35 L150,38 L155,39"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56546" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="4">4</td><td class="name-td"><div class="logo-container"><img alt="Capitec Bank logo" class="company-logo" data-img-dark-path="/img/company-logos/64/CPI.JO.D.png" data-img-path="/img/company-logos/64/CPI.JO.png" loading="lazy" src="/img/company-logos/64/CPI.JO.png"/></div><div class="name-div"><a href="/capitec-bank/marketcap/"><div class="company-name">Capitec Bank</div><div class="company-code"><span class="rank d-none"></span>CPI.JO</div></a></div></td><td class="td-right" data-sort="29375339100"><span class="currency-symbol-left">$</span>29.37 B</td><td class="td-right" data-sort="25366">$253.66</td><td class="rh-sm" data-sort="-589"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>5.89%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,32 L5,31 L10,33 L15,29 L20,29 L25,26 L30,32 L35,25 L40,25 L45,27 L50,27 L55,25 L60,20 L65,17 L70,15 L75,11 L80,12 L85,10 L90,11 L95,3 L100,6 L105,7 L110,7 L115,6 L120,10 L125,6 L130,6 L135,12 L140,24 L145,22 L150,24 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="11487" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="5">5</td><td class="name-td"><div class="logo-container"><img alt="FirstRand logo" class="company-logo" loading="lazy" src="/img/company-logos/64/FSR.JO.png"/></div><div class="name-div"><a href="/firstrand/marketcap/"><div class="company-name">FirstRand</div><div class="company-code"><span class="rank d-none"></span>FSR.JO</div></a></div></td><td class="td-right" data-sort="29298359900"><span class="currency-symbol-left">$</span>29.29 B</td><td class="td-right" data-sort="523.95">$5.24</td><td class="rh-sm" data-sort="-623"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>6.23%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,23 L5,27 L10,28 L15,23 L20,26 L25,23 L30,24 L35,20 L40,19 L45,21 L50,21 L55,19 L60,21 L65,18 L70,16 L75,15 L80,17 L85,14 L90,16 L95,7 L100,8 L105,7 L110,9 L115,5 L120,10 L125,3 L130,4 L135,14 L140,27 L145,24 L150,24 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56337" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="6">6</td><td class="name-td"><div class="logo-container"><img alt="Standard Bank Group logo" class="company-logo" loading="lazy" src="/img/company-logos/64/SBK.JO.png"/></div><div class="name-div"><a href="/standard-bank-group/marketcap/"><div class="company-name">Standard Bank Group</div><div class="company-code"><span class="rank d-none"></span>SBK.JO</div></a></div></td><td class="td-right" data-sort="28469708700"><span class="currency-symbol-left">$</span>28.46 B</td><td class="td-right" data-sort="1758.33">$17.58</td><td class="rh-sm" data-sort="-499"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>4.99%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,36 L5,36 L10,34 L15,32 L20,35 L25,33 L30,33 L35,24 L40,21 L45,22 L50,20 L55,21 L60,22 L65,18 L70,18 L75,16 L80,16 L85,14 L90,12 L95,4 L100,4 L105,9 L110,7 L115,5 L120,7 L125,3 L130,7 L135,8 L140,26 L145,21 L150,24 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56554" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="7">7</td><td class="name-td"><div class="logo-container"><img alt="MTN Group logo" class="company-logo" data-img-dark-path="/img/company-logos/64/MTN.JO.D.png" data-img-path="/img/company-logos/64/MTN.JO.png" loading="lazy" src="/img/company-logos/64/MTN.JO.png"/></div><div class="name-div"><a href="/mtn-group/marketcap/"><div class="company-name">MTN Group</div><div class="company-code"><span class="rank d-none"></span>MTN.JO</div></a></div></td><td class="td-right" data-sort="20899611500"><span class="currency-symbol-left">$</span>20.89 B</td><td class="td-right" data-sort="1156.84">$11.57</td><td class="rh-sm" data-sort="-479"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>4.79%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,32 L5,41 L10,34 L15,33 L20,37 L25,36 L30,35 L35,31 L40,28 L45,29 L50,41 L55,32 L60,27 L65,23 L70,22 L75,19 L80,22 L85,19 L90,19 L95,14 L100,20 L105,16 L110,19 L115,16 L120,7 L125,9 L130,5 L135,3 L140,13 L145,14 L150,11 L155,23"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="34668" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="8">8</td><td class="name-td"><div class="logo-container"><img alt="Vodacom
 logo" class="company-logo" loading="lazy" src="/img/company-logos/64/VOD.JO.png"/></div><div class="name-div"><a href="/vodacom/marketcap/"><div class="company-name">Vodacom
</div><div class="company-code"><span class="rank d-none"></span>VOD.JO</div></a></div></td><td class="td-right" data-sort="18083435100"><span class="currency-symbol-left">$</span>18.08 B</td><td class="td-right" data-sort="935.952">$9.36</td><td class="rh-sm" data-sort="-241"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>2.41%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,38 L5,41 L10,31 L15,31 L20,37 L25,35 L30,33 L35,27 L40,22 L45,24 L50,29 L55,25 L60,22 L65,21 L70,23 L75,20 L80,22 L85,17 L90,17 L95,12 L100,17 L105,14 L110,13 L115,7 L120,5 L125,11 L130,6 L135,3 L140,15 L145,12 L150,14 L155,22"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56600" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="9">9</td><td class="name-td"><div class="logo-container"><img alt="Impala Platinum logo" class="company-logo" data-img-dark-path="/img/company-logos/64/IMP.JO.D.png" data-img-path="/img/company-logos/64/IMP.JO.png" loading="lazy" src="/img/company-logos/64/IMP.JO.png"/></div><div class="name-div"><a href="/impala-platinum/marketcap/"><div class="company-name">Impala Platinum</div><div class="company-code"><span class="rank d-none"></span>IMP.JO</div></a></div></td><td class="td-right" data-sort="14430171200"><span class="currency-symbol-left">$</span>14.43 B</td><td class="td-right" data-sort="1608.72">$16.09</td><td class="rh-sm" data-sort="-195"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>1.95%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,16 L5,10 L10,3 L15,6 L20,3 L25,4 L30,22 L35,33 L40,27 L45,25 L50,35 L55,38 L60,36 L65,35 L70,31 L75,32 L80,38 L85,39 L90,40 L95,34 L100,37 L105,32 L110,27 L115,25 L120,20 L125,15 L130,8 L135,12 L140,34 L145,31 L150,39 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="3197" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="10">10</td><td class="name-td"><div class="logo-container"><img alt="Harmony Gold logo" class="company-logo" loading="lazy" src="/img/company-logos/64/HMY.png"/></div><div class="name-div"><a href="/harmony-gold/marketcap/"><div class="company-name">Harmony Gold</div><div class="company-code"><span class="rank d-none"></span>HMY</div></a></div></td><td class="td-right" data-sort="12235589632"><span class="currency-symbol-left">$</span>12.23 B</td><td class="td-right" data-sort="1959">$19.59</td><td class="rh-sm" data-sort="20"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.20%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,20 L5,18 L10,17 L15,14 L20,3 L25,12 L30,30 L35,32 L40,30 L45,31 L50,41 L55,35 L60,29 L65,30 L70,28 L75,39 L80,32 L85,32 L90,39 L95,37 L100,36 L105,32 L110,27 L115,29 L120,29 L125,23 L130,22 L135,23 L140,34 L145,36 L150,40 L155,40"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56504" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="11">11</td><td class="name-td"><div class="logo-container"><img alt="Sanlam logo" class="company-logo" data-img-dark-path="/img/company-logos/64/SLM.JO.D.png" data-img-path="/img/company-logos/64/SLM.JO.png" loading="lazy" src="/img/company-logos/64/SLM.JO.png"/></div><div class="name-div"><a href="/sanlam/marketcap/"><div class="company-name">Sanlam</div><div class="company-code"><span class="rank d-none"></span>SLM.JO</div></a></div></td><td class="td-right" data-sort="11583542600"><span class="currency-symbol-left">$</span>11.58 B</td><td class="td-right" data-sort="554.859">$5.55</td><td class="rh-sm" data-sort="-355"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>3.55%</span></td><td class="p-0 sparkline-td red"><svg><path d="M0,13 L5,14 L10,11 L15,11 L20,15 L25,9 L30,18 L35,9 L40,8 L45,17 L50,19 L55,19 L60,19 L65,14 L70,17 L75,15 L80,17 L85,12 L90,11 L95,5 L100,6 L105,5 L110,5 L115,4 L120,7 L125,3 L130,5 L135,11 L140,21 L145,19 L150,32 L155,41"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="56775" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="12">12</td><td class="name-td"><div class="logo-container"><img alt="Discovery Limited logo" class="company-logo" data-img-dark-path="/img/company-logos/64/DSY.JO.D.png" data-img-path="/img/company-logos/64/DSY.JO.png" loading="lazy" src="/img/company-logos/64/DSY.JO.png"/></div><div class="name-div"><a href="/discovery-limited/marketcap/"><div class="company-name">Discovery Limited</div><div class="company-code"><span class="rank d-none"></span>DSY.JO</div></a></div></td><td class="td-right" data-sort="10274029900"><span class="currency-symbol-left">$</span>10.27 B</td><td class="td-right" data-sort="1527.51">$15.28</td><td class="rh-sm" data-sort="-235"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>2.35%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,38 L5,39 L10,41 L15,39 L20,40 L25,35 L30,33 L35,30 L40,29 L45,31 L50,32 L55,30 L60,32 L65,25 L70,28 L75,29 L80,35 L85,31 L90,31 L95,26 L100,28 L105,27 L110,27 L115,23 L120,24 L125,3 L130,4 L135,8 L140,6 L145,8 L150,6 L155,13"></path></svg></td><td>🇿🇦 <span class="responsive-hidden">South Africa</span></td></tr><tr><td class="fav"><img alt="favorite icon" data-id="6973" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="13">13</td><td class="name-td"><div class="logo-container"><img alt="Sibanye-Stillwater
 logo" class="company-logo" data-img-dark-path="/img/company-logos/64/SBSW.D.png" data-img-path="/img/company-logos/64/SBSW.png" loading="lazy" src="/img/company-logos/64/SBSW.png"/></div><div class="name-div"><a href="/sibanye-stillwater/marketcap/"><div class="company-name">Sibanye-Stillwater

In [13]:
sa_titles = table.find_all('th')

In [16]:
sa_table_titles = [title.text.strip() for title in sa_titles]
print(sa_table_titles)

['', 'Rank', 'Name', 'Market Cap', 'Price', 'Today', 'Price (30 days)', 'Country']

In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame(columns = sa_table_titles)
df

Empty DataFrame
Columns: [, Rank, Name, Market Cap, Price, Today, Price (30 days), Country]
Index: []

In [19]:
column_data = table.find_all('tr')

In [20]:
for row in column_data[1:]:
    cells = row.find_all('td')

    row_data = []
    for cell in cells:
        text = cell.get_text(" ", strip=True)   # joins broken lines with spaces
        row_data.append(text)

    if not row_data:
        continue

    if any("Close Ad X" in cell for cell in row_data):
        continue

    if len(row_data) == len(df.columns):
        df.loc[len(df)] = row_data
    else:
        print("Skipped row:", row_data, "Length:", len(row_data))

df

,,Rank,Name,Market Cap,Price,Today,Price (30 days),Country
0,,1,AngloGold Ashanti AU,$ 53.80 B,$106.54,1.25%,,🇿🇦 South Africa
1,,2,Gold Fields GFI,$ 45.14 B,$50.44,0.68%,,🇿🇦 South Africa
2,,3,Naspers NPSNY,$ 40.61 B,$10.58,0.47%,,🇿🇦 South Africa
3,,4,Capitec Bank CPI.JO,$ 29.37 B,$253.66,5.89%,,🇿🇦 South Africa
4,,5,FirstRand FSR.JO,$ 29.29 B,$5.24,6.23%,,🇿🇦 South Africa
5,,6,Standard Bank Group SBK.JO,$ 28.46 B,$17.58,4.99%,,🇿🇦 South Africa
6,,7,MTN Group MTN.JO,$ 20.89 B,$11.57,4.79%,,🇿🇦 South Africa
7,,8,Vodacom VOD.JO,$ 18.08 B,$9.36,2.41%,,🇿🇦 South Africa
8,,9,Impala Platinum IMP.JO,$ 14.43 B,$16.09,1.95%,,🇿🇦 South Africa
9,,10,Harmony Gold HMY,$ 12.23 B,$19.59,0.20%,,🇿🇦 South Africa
10,,11,Sanlam SLM.JO,$ 11.58 B,$5.55,3.55%,,🇿🇦 South Africa
11,,12,Discovery Limited DSY.JO,$ 10.27 B,$15.28,2.35%,,🇿🇦 South Africa
12,,13,Sibanye-Stillwater SBSW,$ 10.19 B,$14.10,1.05%,,🇿🇦 South Africa
13,,14,Bid Corp BID.JO,$ 8.48 B,$25.25,1.05%,,🇿🇦 South Africa
14,,15,Shoprite SHP.JO,$ 8.39 B,$15.52,2.37%,,🇿🇦 South Africa
15,,16,Nedbank NED.JO,$ 7.75 B,$16.67,3.28%,,🇿🇦 South Africa
16,,17,OUTsurance Group OUT.JO,$ 6.39 B,$4.14,2.04%,,🇿🇦 South Africa
17,,18,Remgro Limited REM.JO,$ 5.95 B,$10.71,3.39%,,🇿🇦 South Africa
18,,19,Sasol SSL,$ 5.71 B,$8.96,4.19%,,🇿🇦 South Africa
19,,20,Pepkor PPH.JO,$ 5.34 B,$1.45,4.45%,,🇿🇦 South Africa
20,,21,The Bidvest Group BVT.JO,$ 4.81 B,$14.16,3.48%,,🇿🇦 South Africa
21,,22,Clicks Group CLS.JO,$ 4.18 B,$17.88,3.40%,,🇿🇦 South Africa
22,,23,Aspen Pharmacare APN.JO,$ 3.69 B,$8.32,3.26%,,🇿🇦 South Africa
23,,24,Old Mutual OMU.JO,$ 3.68 B,$0.88,3.96%,,🇿🇦 South Africa
24,,25,Growthpoint Properties GRT.JO,$ 3.49 B,$1.03,3.38%,,🇿🇦 South Africa
25,,26,Exxaro Resources EXX.JO,$ 2.90 B,$12.02,3.48%,,🇿🇦 South Africa
26,,27,DRDGOLD DRD,$ 2.89 B,$32.94,0.37%,,🇿🇦 South Africa
27,,28,Ninety One Group N91.L,$ 2.84 B,$3.14,3.06%,,🇿🇦 South Africa
28,,29,Momentum Metropolitan MTM.JO,$ 2.77 B,$2.16,4.48%,,🇿🇦 South Africa
29,,30,Santam SNT.JO,$ 2.73 B,$25.07,1.97%,,🇿🇦 South Africa
30,,31,Tiger Brands TBS.JO,$ 2.72 B,$17.99,2.56%,,🇿🇦 South Africa
31,,32,Mr Price Group MRP.JO,$ 2.66 B,$10.33,2.57%,,🇿🇦 South Africa
32,,33,Redefine Properties RDF.JO,$ 2.66 B,$0.38,3.20%,,🇿🇦 South Africa
33,,34,African Rainbow Minerals ARI.JO,$ 2.53 B,$12.91,6.39%,,🇿🇦 South Africa
34,,35,AVI Limited AVI.JO,$ 2.08 B,$6.26,3.21%,,🇿🇦 South Africa
35,,36,Telkom SA TKG.JO,$ 1.92 B,$3.91,1.80%,,🇿🇦 South Africa
36,,37,Dis-Chem Pharmacies DCP.JO,$ 1.78 B,$2.09,2.09%,,🇿🇦 South Africa
37,,38,Fortress REIT FFB.JO,$ 1.75 B,$1.44,3.12%,,🇿🇦 South Africa
38,,39,The Foschini Group TFG.JO,$ 1.45 B,$4.52,4.05%,,🇿🇦 South Africa
39,,40,Barloworld BAW.JO,$ 1.37 B,$7.36,0.00%,,🇿🇦 South Africa
40,,41,Life Healthcare Group LHC.JO,$ 0.97 B,$0.68,2.07%,,🇿🇦 South Africa
41,,42,Pick n Pay Stores PIK.JO,$ 0.82 B,$1.13,0.75%,,🇿🇦 South Africa
42,,43,Italtile ITE.JO,$ 0.63 B,$0.54,1.11%,,🇿🇦 South Africa
43,,44,Sappi SAP.JO,$ 0.57 B,$0.94,3.57%,,🇿🇦 South Africa
44,,45,Lesaka Technologies LSAK,$ 0.39 B,$4.66,2.19%,,🇿🇦 South Africa
45,,46,Absa Bank ABSP.JO,$ 0.24 B,$55.30,0.00%,,🇿🇦 South Africa
46,,47,Nutun Limited NTU.JO,$ 59.07 M,$0.07531,0.00%,,🇿🇦 South Africa

In [26]:
df.to_csv(
    r'C:\Users\sgxav\OneDrive\Documents\Data Analyst Transition\Data Analyst BootCamp\Python\companies_data.csv',
    index=False
)